name: Slang lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  slang:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Run slang
        uses: pulp-platform/pulp-actions/slang@nw/slang
        with:
          bender-flags: '-t synth_test'
          slang-flags: '--top axi_synth_bench'
