name: Slang lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  slang:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install bender
        uses: pulp-platform/pulp-actions/bender-install@v2.4.5

      - name: Generate file list
        shell: bash
        run: bender script flist-plus -t synth_test > sources.flist

      - name: Run slang
        uses: pulp-platform/pulp-actions/slang@nw/slang
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          slang-flags: '-f sources.flist --top axi_synth_bench -f .github/workflows/slang-flags.f'
